name: Help / Question
description: Need help?
title: "[Help]: "
labels: ["help"]
body:
  - type: markdown
    attributes:
      value: |
        I've considered if setting 'FlutterBluePlus.setLogLevel(LogLevel.verbose)' would help me solve my issue.
  - type: markdown
    attributes:
      value: |
        I've looked at the README "Common Problems" section
  - type: input
    id: fbp-version
    attributes:
      label: FlutterBluePlus Version
      description: run `flutter pub deps` in your project
      placeholder: ex. 1.12.7
    validations:
      required: true
  - type: input
    id: flutter-version
    attributes:
      label: Flutter Version
      description: run `flutter --version` in your project
      placeholder: ex. 3.10.6
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What OS?
      description: please add this to your title
      multiple: true
      options:
        - Android
        - iOS
        - macOS
        - All
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of iOS/Android/MacOS are you on?
      placeholder: ex. iOS 12.3.1
    validations:
      required: true
  - type: input
    id: ble-module
    attributes:
      label: Bluetooth Module
      description: What ble module is your device using?
      placeholder: ex. Arduino HC-08, Espressif esp32-s2, TI CC2541, Nordic nRF52840, NXP QN908x
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Ask your question
      placeholder: Please describe your question in detail
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste *ALL* logs!
      placeholder: Include logs from the very begining!
      render: shell
    validations:
      required: true
